// Canonical skill -> alias keywords used to detect the skill inside free-form resume text.
// Matching is case-insensitive and word-boundary based (see resumeParser.ts).
export const SKILL_KEYWORDS: Record<string, string[]> = {
  "JavaScript": ["javascript", "js", "es6", "ecmascript"],
  "TypeScript": ["typescript", "ts"],
  "Python": ["python", "py"],
  "Java": ["java"],
  "C++": ["c\\+\\+", "cpp"],
  "C#": ["c#", "\\.net", "dotnet"],
  "Go": ["golang", "\\bgo\\b"],
  "SQL": ["sql", "mysql", "postgres", "postgresql", "sqlite", "t-sql"],
  "HTML/CSS": ["html", "css", "sass", "scss", "tailwind"],
  "React": ["react", "react\\.js", "reactjs", "next\\.js", "nextjs"],
  "Angular": ["angular"],
  "Vue": ["vue", "vue\\.js"],
  "Node.js": ["node", "node\\.js", "nodejs", "express"],
  "REST APIs": ["rest api", "restful", "\\bapi\\b", "api design"],
  "GraphQL": ["graphql"],
  "Git": ["git", "github", "gitlab", "version control"],
  "Docker": ["docker", "containeriz"],
  "Kubernetes": ["kubernetes", "k8s"],
  "AWS": ["aws", "amazon web services", "ec2", "s3", "lambda"],
  "Azure": ["azure"],
  "GCP": ["gcp", "google cloud"],
  "CI/CD": ["ci/cd", "continuous integration", "continuous deployment", "jenkins", "github actions"],
  "Linux": ["linux", "unix", "bash", "shell scripting"],
  "Data Structures & Algorithms": ["data structures", "algorithms", "dsa", "leetcode"],
  "System Design": ["system design", "distributed systems", "scalability", "microservices"],
  "Machine Learning": ["machine learning", "\\bml\\b", "scikit-learn", "sklearn"],
  "Deep Learning": ["deep learning", "neural network", "tensorflow", "pytorch", "keras"],
  "NLP": ["nlp", "natural language processing", "large language model", "\\bllm\\b"],
  "Data Analysis": ["data analysis", "data analytics", "pandas", "numpy"],
  "Data Visualization": ["data visualization", "tableau", "power bi", "powerbi", "matplotlib", "seaborn"],
  "Statistics": ["statistics", "statistical analysis", "a/b testing", "hypothesis testing"],
  "Excel": ["excel", "spreadsheet", "vlookup", "pivot table"],
  "Product Management": ["product management", "product manager", "product roadmap", "prd\\b", "product strategy"],
  "Agile/Scrum": ["agile", "scrum", "kanban", "jira", "sprint planning"],
  "Stakeholder Management": ["stakeholder management", "stakeholder", "cross-functional"],
  "UX Research": ["ux research", "user research", "usability testing", "user interviews"],
  "UI/UX Design": ["ui/ux", "ux design", "ui design", "user experience", "user interface", "wireframe", "prototyp"],
  "Figma": ["figma", "sketch\\b", "adobe xd"],
  "QA/Testing": ["quality assurance", "\\bqa\\b", "test automation", "selenium", "cypress", "unit testing", "test cases"],
  "Cybersecurity Fundamentals": ["cybersecurity", "information security", "infosec", "penetration testing", "vulnerability assessment"],
  "Networking": ["networking", "tcp/ip", "dns\\b", "firewall"],
  "Project Management": ["project management", "pmp\\b", "gantt", "project plan"],
  "Communication": ["communication skills", "presentation skills", "public speaking"],
  "Leadership": ["leadership", "team lead", "mentoring", "managed a team"],
  "Financial Analysis": ["financial analysis", "financial modeling", "forecasting", "budgeting"],
  "Sales": ["sales", "quota", "crm\\b", "salesforce", "lead generation"],
  "Marketing": ["marketing", "seo\\b", "sem\\b", "content strategy", "campaign management"],
  "R": ["\\br\\b programming", "\\brstudio\\b"],
  "Spark": ["spark", "hadoop", "big data"],
  "Mobile Development": ["ios development", "android development", "swift", "kotlin", "react native", "flutter"],
};

export function getAllSkillNames(): string[] {
  return Object.keys(SKILL_KEYWORDS);
}
